service:
  name: lambda-template

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'development'}
  region: ${opt:region, 'us-west-2'}
  environment:
    NODE_ENV: ${opt:stage, 'development'}

functions:
  collect-analytics-data:
    handler: src/main.handler
    events:
      - schedule: cron(0/5 * * * ? *)
      - http:
          method: GET
          path: /
